### ISSUE TITLE
something error with /mbplanner_node/FreeFrustParams load

### ISSUE THREAD

**Issue by Tina1994** [unr-arl/mbplanner_ros#6]
Hi, first thanks for you open source code. And  I am testing the proposed launch file mbplanner_m100_sim.launch with melodic branch, and countered the following problem.Could you tell me how to deal with this situation? Thanks a lot

Loading: /mbplanner_node/FreeFrustumParams
namespace_name:/mbplanner_node/FreeFrustumParams
[ERROR][File: /home/tina1994/CM_PHD_CODE/src/mbplanner_ws/src/exploration/mbplanner_ros/planner_common/src/params.cpp] [Line: 235]
Param is not set: /mbplanner_node/FreeFrustumParams/sensor_list

Loading: /mbplanner_node/BoundedSpaceParams/Local
[WARN][File: /home/tina1994/CM_PHD_CODE/src/mbplanner_ws/src/exploration/mbplanner_ros/planner_common/src/params.cpp] [Line: 431]
Param is not set: /global_planner_node/BoundedSpaceParams/Global/min_extension. Setting to default value: {0,0,0}

[WARN][File: /home/tina1994/CM_PHD_CODE/src/mbplanner_ws/src/exploration/mbplanner_ros/planner_common/src/params.cpp] [Line: 442]
Param is not set: /global_planner_node/BoundedSpaceParams/Global/max_extension. Setting to default value: {0,0,0}

**Comment by MihirDharmadhikari** [comment]
Hello @Tina1994 ,

Thank you for pointing this out. The error message shown is because the FreeFrustumParams not set in the config file. These params are not used at the moment so not having them in the config file won't cause any problem. They are not included in the default config file provided for the same reason. However, as this can cause confusion, I have changed the message displayed from error to warning when the params are not set. The PR #7 solves this problem.
Please let me know if you have any further questions.

Thank you,
Mihir
